### ISSUE TITLE
No module named "modbus_tk"

### ISSUE THREAD

**Issue by HazardousCoder** [Osama29/NILM#1]
I keep getting this error all the time and i tried download modbus but it didn't work, how can i solve this issue

```powershell
Traceback (most recent call last):
  File "/home/raspberrypi/PZEM-004t Raspberry Pi.py", line 4, in <module>
     import modbus_tk.defines as cst
ModuleNotFouundError: No module named 'modbus_tk'

------------------
(program exited with code: 1)
Press return to continue
```

I followed all the tutorial and it still didn't fix the issue

**Comment by Osama29** [comment]
### No Module named 'modbus_tk'
if you were trying to run `PZEM-004t Raspberry Pi.py` and it showed the following error:
```powershell
Traceback (most recent call last):
  File "/home/raspberrypi/PZEM-004t Raspberry Pi.py", line 4, in <module>
     import modbus_tk.defines as cst
ModuleNotFouundError: No module named 'modbus_tk'

------------------
(program exited with code: 1)
Press return to continue
```
Then all you have to do is to run this comand in the terminal:
```powershell
sudo pip3 install modbus-tk
```

or

```powershell
sudo pip3 install pymodbus-tk
```
both of these can solve your issue

**Comment by HazardousCoder** [comment]
It worked, Thank you very much
